### PR TITLE
Change keyword naming offset to skip in document

### PR DESCRIPTION
**Pull request by HMarzban**
#25

### CODE REVIEW

**Comment by pbatey** [comment]
The confusion around this is due to a an early decision I made to use the keyword 'offset' and convert it to 'skip' internally. In order to maintain backward-compatibility, I'm reluctant to change the keyword default to 'skip'. The good news is that if you prefer the keyword to be 'skip' you can change it in the options:
```
const q2m = require('query-to-mongo')
var query = q2m('name=john&skip=10&limit=10', {keywords:{offset:'skip'}}
```

**Comment by pbatey** [comment]
One thing that I might consider is changing the internal value to 'skip', but make the default keyword setting 'offset' to maintain backward-compatibility. Then deprecate the 'offset' keyword option. Something like:
```
defaultKeywords = {fields:'fields', omit:'omit', sort:'sort', skip:null, offset:'offset', limit:'limit'}
options.keywords.skip = options.keywords.skip || options.keywords.offset
options.keywords = Object.assign(defaultKeywords, options.keywords)
...
if (query[options.keywords.offset]) hash.skip = Number(query[options.keywords.offset])
```

**Comment by HMarzban** [comment]
that's so good, so what's the next step for the keyword option? when you plan to change this?

**Comment by pbatey** [comment]
Check out my response to #25 -- I clarify the original reasoning behind how the options are formatted. And show an example of how it can be used with **Mongoose 6.0.0**.

**Comment by pbatey** [comment]
Thanks for the update! 👍 

And sorry I didn't understand the description in #25 (I was over-thinking the issue!)

**Pull request merged**
